Repository Azure/Bridge-To-Kubernetes, pull requests merged in 2023-05, with the labels that each got.

#210 Resolves Warning SYSLIB021 - Derived cryptographic types are obsolete
  src/common.tests/Logging/MacAddressHash/MacInformationProviderTests.cs
  src/common/Logging/MacAddressHash/FipsCompliantSha.cs
  src/common/Logging/MacAddressHash/MACInformationProvider.cs
Labels: e2e testing, review done

#261 Fixed exception rethrow
  src/library/Client/ManagementClients/KubeConfigManagementClient.cs
Labels: review done

#253 Fixes warnings for nullable reference types being used
  src/common/Json/JsonHelpers.cs
Labels: review done

#255 Fixed swaped arguments
  src/common.tests/FixedSizeStringBuilderTests.cs
  src/library.tests/PortMappingManagerTest.cs
  src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs
Labels: review done

#227 226 - add ns to env vars when workload ns != service ns
  src/library.tests/LocalEnvironmentManagerTests.cs
  src/library/Connect/LocalEnvironmentManager.cs
Labels: good first issue, review done

#209 Refactoring Json serialization
  src/LocalAgent/LocalAgentApp.cs
  src/common.tests/JsonHelperTests.cs
  src/common.tests/JsonHelpersTest.cs
  src/common.tests/Logging/ExtensionsTests.cs
  src/common/Extensions/HttpExtensions.cs
  src/common/IO/FileSystem.cs
  src/common/IO/IFileSystem.cs
  src/common/IO/Output/ConsoleOutput.cs
  src/common/Json/JsonHelpers.cs
  src/common/Json/JsonPropertyHelpers.cs
  src/common/Logging/Extensions.cs
  src/common/Logging/Loggers/TextLoggerBase.cs
  src/common/Logging/MacAddressHash/VSCodeStorageReader.cs
  src/common/Logging/PII.cs
  src/common/Logging/PIIException.cs
  src/common/Models/Kubernetes/Pod.cs
  src/devhostAgent.restorationjob.tests/RestorationJobAppTests.cs
  src/devhostagent.restorationjob/RestorationJobApp.cs
  src/library/Client/ManagementClients/ConnectManagementClient.cs
  src/library/Client/ManagementClients/KubernetesManagementClient.cs
  src/library/Connect/Environment/LocalProcessConfig.cs
  src/library/Connect/KubernetesRemoteEnvironmentManager.cs
Labels: e2e testing, review done
