Repository Azure/Bridge-To-Kubernetes, pull requests merged in 2023-06, with the labels that each got.

#258 to support different auth providers with kubectl proxy
  build-pipelines-PR.yml
  src/common.tests/Kubernetes/K8sClientFactoryTests.cs
  src/common.tests/Kubernetes/KubernetesClientTests.cs
  src/common.tests/TestData/simpleconfig.yml
  src/common.tests/common.tests.csproj
  src/common/EnvironmentVariables.cs
  src/common/IEnvironmentVariables.cs
  src/common/Kubernetes/K8sClientFactory.cs
  src/common/Kubernetes/KubernetesWatcher.cs
  src/common/common.csproj
  src/library/Client/ServiceClients/Handlers/ServiceClientCredentialsHttpHandler.cs
  src/routingmanager/routingmanager.csproj
Labels: review done

#248 Removed unused code
  src/common.tests/ApiVersionHelperTests.cs
  src/common.tests/EscapeUtilitiesTests.cs
  src/common.tests/ReleaseUtilitiesTests.cs
  src/common.tests/UrlParsingTests.cs
  src/common/Models/Channel/CommandExecuteRequest.cs
  src/common/Models/Channel/ContainerInfo.cs
  src/common/Models/Channel/ExecuteRequest.cs
  src/common/Models/Channel/RunningProcessInfo.cs
  src/common/Models/Channel/StreamOutputBlock.cs
  src/common/Models/Docker/DockerCommand.cs
  src/common/Models/Docker/DockerInstruction.cs
  src/common/Models/Docker/DockerfileParser.cs
  src/common/Models/Docker/TextSpan.cs
  src/common/Models/Kubernetes/Container.cs
  src/common/Models/Kubernetes/ContainerState.cs
  src/common/Models/Kubernetes/Endpoint.cs
  src/common/Models/Kubernetes/Ingress.cs
  src/common/Models/Kubernetes/KubernetesContainer.cs
  src/common/Models/Kubernetes/Pod.cs
  src/common/Models/Kubernetes/PublicUrlInfo.cs
  src/common/Models/Kubernetes/Service.cs
  src/common/Models/LocalConnect/ContainerVolumeMappingInfo.cs
  src/common/Models/Sync/FileItem.cs
  src/common/Models/Sync/SyncRequestBlock.cs
  src/common/Models/Sync/SyncRequestKind.cs
  src/common/Models/Sync/SyncResponse.cs
  src/common/Models/Sync/SyncResponseKind.cs
  src/common/Models/Sync/SyncState.cs
  src/common/Models/Sync/SyncStateResponse.cs
  src/common/Models/Values.cs
  src/common/Utilities/ApiVersionHelper.cs
  src/common/Utilities/EscapeUtilities.cs
  src/common/Utilities/HashHelpers.cs
  src/common/Utilities/HttpClientExceptionStrategy.cs
  src/common/Utilities/NoOpDisposable.cs
  src/common/Utilities/ReleaseUtilities.cs
  src/common/Utilities/ScopeSetting.cs
  src/common/Utilities/UrlParsing.cs
  src/library/Client/IterationTrackingSession.cs
  src/library/Client/ManagementClients/KubernetesManagementClient.cs
  src/library/Connect/ContainerIdentifierOption.cs
  src/library/Extensions/OwnedExtensions.cs
  src/library/Extensions/SignalRExtensions.cs
Labels: review done

#282 Update README.md
  README.md
Labels: documentation

#278 named ports fix for headless services
  src/library.tests/LocalEnvironmentManagerTests.cs
  src/library.tests/WorkloadInformationProviderTests.cs
  src/library/Connect/WorkloadInformationProvider.cs
Labels: review done

#251 Ignore warning CS8002 when building in debug mode
  src/EndpointManagerLauncher/endpointmanagerlauncher.csproj
  src/LocalAgent/LocalAgent.csproj
  src/common.tests/common.tests.csproj
  src/common/common.csproj
  src/devhostAgent.restorationjob.tests/devhostAgent.restorationjob.tests.csproj
  src/devhostagent.restorationjob/devhostAgent.restorationjob.csproj
  src/devhostagent/devhostAgent.csproj
  src/dsc.tests/dsc.tests.csproj
  src/dsc/dsc.csproj
  src/endpointmanager.tests/endpointmanager.tests.csproj
  src/endpointmanager/endpointmanager.csproj
  src/library.tests/library.tests.csproj
  src/library/library.csproj
  src/routingmanager.tests/routingmanager.tests.csproj
  src/routingmanager/routingmanager.csproj
  src/testhelpers/testhelpers.csproj
Labels: review done

#286 Remove deprecated dependencies from samples
  samples/ingress/frontend/package-lock.json
  samples/ingress/frontend/package.json
  samples/ingress/frontend/server.js
  samples/todo-app/frontend/package-lock.json
  samples/todo-app/frontend/package.json
Labels: needs review
