Repository Azure/Bridge-To-Kubernetes, pull requests merged in 2023-04, with the labels that each got.

#232 Enable auto review using chatgpt.
  .github/workflows/chatgpt-review.yml
Labels: enhancement

#175 fix case sensitivity and update base images for mariner
  deployment/settings/services/imagetag.setting
  src/devhostagent.restorationjob/Dockerfile
  src/devhostagent/Dockerfile
  src/routingmanager/Dockerfile
Labels: e2e testing

#230 Added new editor config file for consistent code formatting
  src/.editorconfig
  src/all.sln
Labels: needs review

#213 Added SupportedOSPlatformGuard and new improved operating system identification
  src/common/IO/IPlatform.cs
  src/common/IO/Platform.cs
Labels: e2e testing

#216 Remove root permissions for creating symlink in user's local bin folder
  scripts/install.sh
Labels: good first issue, waiting for response, no-github-issue-linked

#178 Modified method to have one set of env variables and added UTs
  src/library.tests/KubernetesRemoteEnvironmentManagerTests.cs
  src/library/Connect/KubernetesRemoteEnvironmentManager.cs
Labels: e2e testing

#237 Json patch issue fix for stateful sets
  deployment/settings/services/imagetag.setting
  src/devhostagent/Dockerfile
  src/library.tests/KubernetesRemoteEnvironmentManagerTests.cs
  src/library/Connect/KubernetesRemoteEnvironmentManager.cs
Labels: bug-fix

#231 rm timeout override from getContainerEnv
  src/common/Kubernetes/KubernetesClient.cs
Labels: e2e testing

#191 Removes package references in favour of FrameworkReference
  src/LocalAgent/LocalAgent.csproj
  src/common/common.csproj
  src/devhostagent/devhostAgent.csproj
  src/dsc/dsc.csproj
  src/endpointmanager/endpointmanager.csproj
  src/library.tests/LocalEnvironmentManagerTests.cs
  src/library.tests/library.tests.csproj
  src/routingmanager/routingmanager.csproj
Labels: e2e testing

#257 Fixes invalid xml documentation tags
  src/common/EndpointManagement/IHostsFileManager.cs
  src/common/Logging/LoggingUtils.cs
  src/common/Socket/ISocket.cs
Labels: review done
